services:

  nginx:
    image: nginx:1.21.3
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - users

  users:
    image: alexquesada/userservice:0.0.2
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-user:3306/users
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=create-drop
    ports:
      - "8081:8081"
    depends_on:
      mysql-user:
        condition: service_healthy
    networks:
      - app-network

  mysql-user:
    image: mysql:8.0.32
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app-network

#  mysql-monolith:
#    image: mysql:8.0.32
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: books
#      MYSQL_PASSWORD: password
#      MYSQL_USER: user
#    healthcheck:
#      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
#      interval: 5s
#      timeout: 5s
#      retries: 3
#
#  planner:
#    image: alexquesada/planner:0.0.1
#    command: [ "./wait-for-it.sh", "weather:9090", "--", "./wait-for-it.sh", "topo:8181", "--", "java", "-jar", "planner-0.0.1-SNAPSHOT.jar"]
#    environment:
#      SPRING_RABBITMQ_HOST: rabbit
#      SPRING_RABBITMQ_PORT: 5672
#      SPRING_RABBITMQ_USERNAME: guest
#      SPRING_RABBITMQ_PASSWORD: guest
#      SPRING_RABBITMQ_VIRTUAL_HOST: /
#      WEATHER_SERVER_HOST: weather
#      WEATHER_SERVER_PORT: 9090
#      TOPO_HOST: topo
#      TOPO_PORT: 8181
#    depends_on:
#      - rabbit
#
#  topo:
#    image: alexquesada/toposervice:0.0.2
#    restart: on-failure
#    ports:
#      - 8181:8181
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydatabase
#    depends_on:
#      - mongo
#
#  weather:
#    image: alexquesada/weatherservice:0.0.0
#    ports:
#      - "9090:9090"
#
#  mysql:
#    image: mysql:8.0.32
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: eoloplantsDB
#      MYSQL_PASSWORD: password
#      MYSQL_USER: user
#    healthcheck:
#      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
#      interval: 5s
#      timeout: 5s
#      retries: 3

networks:
  app-network:
    driver: bridge